/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignmentgui;

import static assignmentgui.CatalogueForm.capacityList;
import static assignmentgui.CatalogueForm.categoryList;
import static assignmentgui.CatalogueForm.priceList;
import static assignmentgui.CatalogueForm.productList;
import java.awt.Component;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Admin
 */
public class DetailsWithMenu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    
    private static int iNo;
    private static double price;
    private static String category,product,capacity;
    LoginForm login = new LoginForm();
    String name = login.getName();
    CatalogueForm cf = new CatalogueForm();
    double totalPrice=cf.getTotalPrice();
    
    public DetailsWithMenu() {
        initComponents();
        
        jPanel1.requestFocusInWindow();
        
        itemNoLabel.setText(null);
        itemNo.setVisible(false);
        deButton.setVisible(false);
        eButton.setVisible(false);
        pComboBox.setVisible(false);
        sRadioButton.setVisible(false);
        mRadioButton.setVisible(false);
        lRadioButton.setVisible(false);
        cButton.setVisible(false);
        jLabel3.setText(null);
        sTextField.setVisible(false);
        sButton.setVisible(false);
        
        DefaultTableModel tblModel=(DefaultTableModel)jTable1.getModel();
        DecimalFormat df = new DecimalFormat("#.00");
        for(int i=0;i<productList.size();i++){
            Object data[]={i+1,categoryList.get(i),productList.get(i),capacityList.get(i),df.format(priceList.get(i))};
            tblModel.addRow(data);
        }
        
        //Auto-resizing column width of table to fit data
        final TableColumnModel columnModel = jTable1.getColumnModel();
        for (int column = 0; column < jTable1.getColumnCount(); column++) {
            int width = 15; // Min width
            for (int row = 0; row < jTable1.getRowCount(); row++) {
                TableCellRenderer renderer = jTable1.getCellRenderer(row, column);
                Component comp = jTable1.prepareRenderer(renderer, row, column);
                width = Math.max(comp.getPreferredSize().width +1 , width);
            }
        if(width > 300)
            width=300;
        columnModel.getColumn(column).setPreferredWidth(width);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        itemNoLabel = new javax.swing.JLabel();
        itemNo = new javax.swing.JTextField();
        deButton = new javax.swing.JButton();
        eButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pComboBox = new javax.swing.JComboBox<>();
        productLabel = new javax.swing.JLabel();
        capacityLabel = new javax.swing.JLabel();
        sRadioButton = new javax.swing.JRadioButton();
        mRadioButton = new javax.swing.JRadioButton();
        lRadioButton = new javax.swing.JRadioButton();
        cButton = new javax.swing.JButton();
        sTextField = new javax.swing.JTextField();
        sButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuAdd = new javax.swing.JMenuItem();
        menuEdit = new javax.swing.JMenuItem();
        menuDelete = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuSearch = new javax.swing.JMenuItem();
        menuDisplay = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuExit = new javax.swing.JMenuItem();

        cButtonGroup.add(sRadioButton);
        cButtonGroup.add(mRadioButton);
        cButtonGroup.add(lRadioButton);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Data");
        setPreferredSize(new java.awt.Dimension(476, 520));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Category", "Product", "Capacity", "Price (RM)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        itemNoLabel.setText("Item No:");

        deButton.setText("Delete");
        deButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deButtonActionPerformed(evt);
            }
        });

        eButton.setText("Edit");
        eButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eButtonActionPerformed(evt);
            }
        });

        pComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Classic Electric Rice Cooker", "Gas Rice Cooker", "Micro-computerized Rice Cooker" }));

        sRadioButton.setBackground(new java.awt.Color(204, 204, 255));
        sRadioButton.setText("Small");

        mRadioButton.setBackground(new java.awt.Color(204, 204, 255));
        mRadioButton.setText("Medium");

        lRadioButton.setBackground(new java.awt.Color(204, 204, 255));
        lRadioButton.setText("Large");

        cButton.setText("Confirm");
        cButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cButtonActionPerformed(evt);
            }
        });

        sTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sTextField.setText("Product");
        sTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sTextFieldFocusGained(evt);
            }
        });

        sButton.setText("Search");
        sButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Item: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(sTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(capacityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(sRadioButton)
                                    .addGap(18, 18, 18)
                                    .addComponent(mRadioButton)
                                    .addGap(18, 18, 18)
                                    .addComponent(lRadioButton))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(productLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(pComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(cButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(itemNoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(itemNo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(deButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(eButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)
                                .addComponent(jLabel3)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(itemNoLabel)
                        .addComponent(itemNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(deButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(eButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(capacityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sRadioButton)
                        .addComponent(mRadioButton)
                        .addComponent(lRadioButton)))
                .addGap(34, 34, 34)
                .addComponent(cButton)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        menuFile.setText("File");

        menuAdd.setText("Add");
        menuAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddActionPerformed(evt);
            }
        });
        menuFile.add(menuAdd);

        menuEdit.setText("Edit");
        menuEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditActionPerformed(evt);
            }
        });
        menuFile.add(menuEdit);

        menuDelete.setText("Delete");
        menuDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDeleteActionPerformed(evt);
            }
        });
        menuFile.add(menuDelete);
        menuFile.add(jSeparator1);

        menuSearch.setText("Search");
        menuSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSearchActionPerformed(evt);
            }
        });
        menuFile.add(menuSearch);

        menuDisplay.setText("Display");
        menuDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDisplayActionPerformed(evt);
            }
        });
        menuFile.add(menuDisplay);
        menuFile.add(jSeparator2);

        menuExit.setText("Exit");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        menuFile.add(menuExit);

        jMenuBar1.add(menuFile);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        // TODO add your handling code here:
         this.setDefaultCloseOperation(DetailsWithMenu.EXIT_ON_CLOSE);
         System.exit(0);
    }//GEN-LAST:event_menuExitActionPerformed

    private void menuAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddActionPerformed
        // TODO add your handling code here:
        
        AddForm af= new AddForm();
        af.setVisible(true);
    }//GEN-LAST:event_menuAddActionPerformed

    private void menuDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDisplayActionPerformed
        // TODO add your handling code here:
        DisplayedForm df = new DisplayedForm(); 
        df.setVisible(true);
        
    }//GEN-LAST:event_menuDisplayActionPerformed

    private void menuDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDeleteActionPerformed
        // TODO add your handling code here:
        itemNoLabel.setText("Item No:");
        itemNo.setText(null);
        itemNo.setVisible(true);
        deButton.setVisible(true);
        
        eButton.setVisible(false);
        jLabel1.setText(null);
        jLabel2.setText(null);
        productLabel.setText(null);
        capacityLabel.setText(null);
        pComboBox.setVisible(false);
        sRadioButton.setVisible(false);
        mRadioButton.setVisible(false);
        lRadioButton.setVisible(false);
        cButton.setVisible(false);
        
        jLabel3.setText(null);
        sTextField.setVisible(false);
        sButton.setVisible(false);
    }//GEN-LAST:event_menuDeleteActionPerformed

    private void deButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deButtonActionPerformed
        // TODO add your handling code here:
        iNo=Integer.parseInt(itemNo.getText());
        totalPrice-=priceList.get(iNo-1);
        DefaultTableModel tblModel=(DefaultTableModel)jTable1.getModel();
        tblModel.removeRow(iNo-1);
        capacityList.remove(iNo-1);
        categoryList.remove(iNo-1);
        priceList.remove(iNo-1);
        productList.remove(iNo-1);
        
        for(int i=0;i<productList.size();i++){
            tblModel.setValueAt(i+1, i, 0);
        }
        
        try(FileWriter Writer = new FileWriter("/Users/Admin/Desktop/ShoppingCart.txt",false)) {
            Writer.write("Name: "+name+"\n");
            Writer.write("|====================================================================================================================================================|\n");
            Writer.write(String.format("| %-40s| %-40s| %-40s | %20s| %n","CATEGORY","PRODUCT","CAPACITY","PRICE(RM)" ));
            Writer.write("|====================================================================================================================================================|\n");
            for(int i=0;i<productList.size();i++){
                Writer.write(String.format("| %-40s| %-40s| %-40s | %20.2f| %n", categoryList.get(i),productList.get(i),capacityList.get(i),priceList.get(i)));
                 Writer.write("|----------------------------------------------------------------------------------------------------------------------------------------------------|\n");
            }
            Writer.write(String.format("| %-125s| %20.2f| %n","TOTAL PRICE:",totalPrice));
            Writer.write("|----------------------------------------------------------------------------------------------------------------------------------------------------|\n");
            Writer.close();
        }catch(IOException e){
            
        }
    }//GEN-LAST:event_deButtonActionPerformed

    private void menuEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditActionPerformed
        // TODO add your handling code here:
        deButton.setVisible(false);
        itemNoLabel.setText("Item No:");
        itemNo.setText(null);
        itemNo.setVisible(true);
        eButton.setVisible(true);
        
        jLabel3.setText(null);
        sTextField.setVisible(false);
        sButton.setVisible(false);
    }//GEN-LAST:event_menuEditActionPerformed

    private void eButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eButtonActionPerformed
        // TODO add your handling code here:
        jLabel1.setText("For your information, you can only change the product and capacity from selected category.");
        jLabel2.setText("Otherwise, you can remove the item then add item from another category.");
        productLabel.setText("Product");
        capacityLabel.setText("Capacity");
        pComboBox.setVisible(true);
        sRadioButton.setVisible(true);
        mRadioButton.setVisible(true);
        lRadioButton.setVisible(true);
        cButton.setVisible(true);
    }//GEN-LAST:event_eButtonActionPerformed

    private void cButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButtonActionPerformed
        // TODO add your handling code here:
        iNo=Integer.parseInt(itemNo.getText());
        
        if(pComboBox.getSelectedIndex()==0 && sRadioButton.isSelected()==true){
            capacity="small";
            price=81.00;
        }else if(pComboBox.getSelectedIndex()==0 && mRadioButton.isSelected()==true){
            capacity="medium";
            price=119.99;
        }else if(pComboBox.getSelectedIndex()==0 && lRadioButton.isSelected()==true){
            capacity="large";
            price=142.00;
        }else if(pComboBox.getSelectedIndex()==1 && sRadioButton.isSelected()==true){
            capacity="small";
            price=399.99;
        }else if(pComboBox.getSelectedIndex()==1 && mRadioButton.isSelected()==true){
            capacity="medium";
            price=479.90;
        }else if(pComboBox.getSelectedIndex()==1 && lRadioButton.isSelected()==true){
            capacity="large";
            price=622.00;
        }else if(pComboBox.getSelectedIndex()==2 && sRadioButton.isSelected()==true){
            capacity="small";
            price=235.00;
        }else if(pComboBox.getSelectedIndex()==2 && mRadioButton.isSelected()==true){
            capacity="medium";
            price=399.89;
        }else if(pComboBox.getSelectedIndex()==2 && lRadioButton.isSelected()==true){
            capacity="large";
            price=575.90;
        }
        
        totalPrice=totalPrice-priceList.get(iNo-1)+price;
        
        productList.set(iNo-1, (String) pComboBox.getSelectedItem());
        capacityList.set(iNo-1, capacity);
        priceList.set(iNo-1, price);
        
        DefaultTableModel tblModel=(DefaultTableModel)jTable1.getModel();
        DecimalFormat df = new DecimalFormat("#.00");
        tblModel.setValueAt((String) pComboBox.getSelectedItem(), iNo-1, 2);
        tblModel.setValueAt(capacity, iNo-1, 3);
        tblModel.setValueAt(df.format(price), iNo-1, 4);
     
        try(FileWriter Writer = new FileWriter("/Users/Admin/Desktop/ShoppingCart.txt",false)) {
            Writer.write("Name: "+name+"\n");
            Writer.write("|====================================================================================================================================================|\n");
            Writer.write(String.format("| %-40s| %-40s| %-40s | %20s| %n","CATEGORY","PRODUCT","CAPACITY","PRICE(RM)" ));
            Writer.write("|====================================================================================================================================================|\n");
            for(int i=0;i<productList.size();i++){
                Writer.write(String.format("| %-40s| %-40s| %-40s | %20.2f| %n", categoryList.get(i),productList.get(i),capacityList.get(i),priceList.get(i)));
                 Writer.write("|----------------------------------------------------------------------------------------------------------------------------------------------------|\n");
            }
            Writer.write(String.format("| %-125s| %20.2f| %n","TOTAL PRICE:",totalPrice));
            Writer.write("|----------------------------------------------------------------------------------------------------------------------------------------------------|\n");
            Writer.close();
        }catch(IOException e){
            
        }
    }//GEN-LAST:event_cButtonActionPerformed

    private void sButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sButtonActionPerformed
        // TODO add your handling code here:
        jLabel3.setText("Item: ");
        for(int i=0;i<productList.size();i++){
            if(productList.get(i).contains(sTextField.getText())==true){
                iNo=i+1;
                jLabel3.setText(jLabel3.getText()+iNo+"- "+productList.get(i)+", ");
            }
        }
        
        
    }//GEN-LAST:event_sButtonActionPerformed

    private void sTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sTextFieldFocusGained
        // TODO add your handling code here:
        sTextField.setText(null);
    }//GEN-LAST:event_sTextFieldFocusGained

    private void menuSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSearchActionPerformed
        // TODO add your handling code here:
        sTextField.setVisible(true);
        sButton.setVisible(true);
        
        deButton.setVisible(false);
        itemNoLabel.setText(null);
        itemNo.setVisible(false);
        eButton.setVisible(false);
        jLabel1.setText(null);
        jLabel2.setText(null);
        productLabel.setText(null);
        capacityLabel.setText(null);
        pComboBox.setVisible(false);
        sRadioButton.setVisible(false);
        mRadioButton.setVisible(false);
        lRadioButton.setVisible(false);
        cButton.setVisible(false);
        
    }//GEN-LAST:event_menuSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailsWithMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailsWithMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailsWithMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailsWithMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailsWithMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cButton;
    private javax.swing.ButtonGroup cButtonGroup;
    private javax.swing.JLabel capacityLabel;
    private javax.swing.JButton deButton;
    private javax.swing.JButton eButton;
    private javax.swing.JTextField itemNo;
    private javax.swing.JLabel itemNoLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton lRadioButton;
    private javax.swing.JRadioButton mRadioButton;
    private javax.swing.JMenuItem menuAdd;
    private javax.swing.JMenuItem menuDelete;
    private javax.swing.JMenuItem menuDisplay;
    private javax.swing.JMenuItem menuEdit;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuItem menuSearch;
    private javax.swing.JComboBox<String> pComboBox;
    private javax.swing.JLabel productLabel;
    private javax.swing.JButton sButton;
    private javax.swing.JRadioButton sRadioButton;
    private javax.swing.JTextField sTextField;
    // End of variables declaration//GEN-END:variables
}
